// <auto-generated />
using System;
using BolaoWebAPI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BolaoWebAPI.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604150208_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bolao")
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BolaoWebAPI.Domain.Entities.Bolao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataSorteio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("ModalidadeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("QuantidadeCotas")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorCota")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ModalidadeId");

                    b.ToTable("Boloes", "bolao");
                });

            modelBuilder.Entity("BolaoWebAPI.Domain.Entities.BolaoParticipante", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BolaoId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Pago")
                        .HasColumnType("bit");

                    b.Property<long>("ParticipanteId")
                        .HasColumnType("bigint");

                    b.Property<int>("QuantidadeCotas")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorCota")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ParticipanteId");

                    b.HasIndex("BolaoId", "ParticipanteId")
                        .IsUnique();

                    b.ToTable("BolaoParticipantes", "bolao");
                });

            modelBuilder.Entity("BolaoWebAPI.Domain.Entities.Jogo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BolaoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Numeros")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BolaoId");

                    b.ToTable("Jogos", "bolao");
                });

            modelBuilder.Entity("BolaoWebAPI.Domain.Entities.Modalidade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumeroMaximo")
                        .HasColumnType("int");

                    b.Property<int>("NumeroMinimo")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeMaximaNumeros")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeMinimaNumeros")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Modalidades", "bolao");
                });

            modelBuilder.Entity("BolaoWebAPI.Domain.Entities.Participante", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Participantes", "bolao");
                });

            modelBuilder.Entity("BolaoWebAPI.Domain.Entities.Resultado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BolaoId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataResultado")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumerosSorteados")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BolaoId");

                    b.ToTable("Resultados", "bolao");
                });

            modelBuilder.Entity("BolaoWebAPI.Domain.Entities.Bolao", b =>
                {
                    b.HasOne("BolaoWebAPI.Domain.Entities.Modalidade", null)
                        .WithMany()
                        .HasForeignKey("ModalidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BolaoWebAPI.Domain.Entities.BolaoParticipante", b =>
                {
                    b.HasOne("BolaoWebAPI.Domain.Entities.Bolao", null)
                        .WithMany()
                        .HasForeignKey("BolaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BolaoWebAPI.Domain.Entities.Participante", null)
                        .WithMany()
                        .HasForeignKey("ParticipanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BolaoWebAPI.Domain.Entities.Jogo", b =>
                {
                    b.HasOne("BolaoWebAPI.Domain.Entities.Bolao", null)
                        .WithMany()
                        .HasForeignKey("BolaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BolaoWebAPI.Domain.Entities.Resultado", b =>
                {
                    b.HasOne("BolaoWebAPI.Domain.Entities.Bolao", null)
                        .WithMany()
                        .HasForeignKey("BolaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
